### ISSUE TITLE
awesome thanks. just a suggestion

### ISSUE THREAD

**Issue by raeffer** [cabberley/HA_RedbackTech#7]
Back from Italy. The motoGP was awesome incase you were wondering :)

I have installed VIA HACS and seems to be working perfectly for me!! Thanks so much!!

My suggestions would be:
1] to add in the README the steps to add the form to a dash board by going to SETTINGS/DEVICES AND SERVICES/REDBACK TECHNOLIGIES/DEVICES then choose your invertor which opens a page that allows you to add the pre configured card to a dashboard
2] just minor but would it be possible for the scheduled ID Selection to be descriptive of the schedule that has been created rather than the random  numbers and letters that it shows currently. (sorry just re read the README and saw this on the TO DO list oopsie)

And lastly a question: If I created a schedule that charged the battery for 30 mins at 3.00am in the morning, would that be recurring until deleted? just that the Redback web portal has a a slider to choose if you want to just run a schedule just once.

Again this is so good!!!!
THANKS

**Comment by cabberley** [comment]
@raeffer Thanks for the feedback. 
1. The simple things you learn! never noticed that simple option the devices screen! I will add that when I can to the readme!
2. Agree its not pretty atm, that's the Unique ID redback creates for a schedule entry. Open to suggestions on what makes sense. I was thinking maybe a combination of the date and start time?

On the recurring vs one time entry. I had a closer look at that. Due to the way Redback have done a couple of things its going to be complicated.
a. The APIs only enable me to create and delete Scheduled once off entries.
b. The recurring entries atm can only be created and deleted via the portal website. But the way they do it, is not pretty, they take the complete list of scheduled/recurring that is presented on that screen and replace whatever was in the backend with the complete new list, they don't update/amend.
c. The recurring entries don't actually get a unique ID.
d. if you want to reset the inverter to Auto either through HA or the portal it will wipe all the scheduled\recurring. You would then be forced to recreate manually in the portal the recurring.
e. I can retrieve the recurring events trough the API and display them in HA (more code required but pretty easy) just can't manipulate them easily.

So if you have some ideas on how you would like it to work, I can take that on board and think about how we could do this. Its all possible just how do we want it to work?

**Comment by raeffer** [comment]
Yes i think date and start time would be good and possibly the mode.

I'm not bothered about recurring entries i just wanted to make sure i didn't need to clear them after each time one ran so as not to have unexpected mode activations.

Ideally for me, as you have a one button press to reset to auto.....would be to have a one button press to "charge battery" or "export power" But I understand the logic in your readme as to why that was problematic.

**Comment by cabberley** [comment]
> Ideally for me, as you have a one button press to reset to auto.....would be to have a one button press to "charge battery" or "export power" But I understand the logic in your readme as to why that was problematic.

So for this I could add a Service to enable you to create a button yourself that calls the service. Which would be more appropriate for "Buyer be ware!" cause you will always run the risk of forgotten you set to charge or discharge and bad things happen to your power bills, particularly if your on Amber or similar spot market rates!

**Comment by raeffer** [comment]
Yes please. i carry the same risk with the web portal anyway :)

**Comment by cabberley** [comment]
@raeffer just made an update and new release should give you everything you asked for

**Comment by cabberley** [comment]
@raeffer Just added Redback Operating Envelopes and some other little updates. Operating Envelopes will enable you to curtail the Redbacks if you have an energy provider that can go negative on a feed in tarrif

**Comment by raeffer** [comment]
cheers mate sounds awesome
am i correct in saying that if you just choose the power mode from the power mode selection dropdown and set the power level then press 'Set inverter Via Portal' button it will keep using the chosen mode until you press 'Reset Invertor To AUTO' 

also I dont understand what operator envelopes are. you reference a wiki to find out more but where is that?

**Comment by cabberley** [comment]
https://github.com/cabberley/HA_RedbackTech/wiki

Yes, it should stay in that mode until you do something else. If you set a schedule for example ot would change to the schedule at the time and duration and when ended return to whatever mode it had been set to via the portal.

Read the wiki on operating envelopes and let me know if that makes sense.

**Comment by cabberley** [comment]
Also just added a beta, which populate a calendar with all your schedules and envelopes if you are using either of them.

**Comment by GrantKeymer** [comment]
Very impressive work @cabberley 👏 

After reading your Wiki, I now have a much better understanding of the capabilities of my Redback SH5000.  Redback have never provided most of this info to their customers.  They leave you to fill in the blanks by yourself and spell it out when you ask for API access, that no support whatsoever will be provided.  You've done a great job in figuring out all this stuff.

Thankfully, there is no such thing as 'Negative Feed-in Tariffs in NZ', but maybe it will come in future.  Thanks to all your work, I'm well prepared just in case.
